# -*- coding: utf-8 -*-
"""All_Agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BnhN9wwCYSxzg2d7TIKm8DFZG41_tUo7
"""

### https://docs.langchain.com/oss/python/integrations/document_loaders

!pip install langchain_openai

!pip install langchain_experimental

from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain_openai import ChatOpenAI

import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/refs/heads/main/CardioGoodFitness-1.csv")

### Display random 10 records
### Describe

df.sample(10)

df.describe(include="all")

from google.colab import userdata
import os
os.environ["OPENAI_API_KEY"]=userdata.get('openai')

from langchain_openai import OpenAI
llm=OpenAI()

agent=create_pandas_dataframe_agent(llm,df,verbose=True,allow_dangerous_code=True)

import warnings
warnings.filterwarnings("ignore")

agent.run("How many rows are there?")

agent.run("How many are using TM 195?")

df['Product'].value_counts()

agent.run("What is the fitness level of 18 years old?")

agent.run("Show the unique Products with piechart")

agent.run("Show the unique Products with interactive piechart ")

agent.run("The Problem Statement is to predict the relationship between Product and Customer Characteristics.")

agent.run("Make KNN model and calculate the accuracy")

agent.run("Is Fitness numerical?")

agent.run("You are wrong?")

agent.run("Why is TM798 count less")

df1=df.copy()

agent=create_pandas_dataframe_agent(llm,[df,df1],verbose=True,allow_dangerous_code=True)

agent.run("Compare the dataframes and show the different records")

### usecase-2 (llm,tool,memory)
#### Import all the packages
#### key
### initialize
### define a function for the tool
### tool-> name,func(defining above),description
### memory-> chat history
### agent-> tool,llm,agent type,memory
### run agent

!pip uninstall -y langchain langchain-core langchain-community langchain-openai
!pip install langchain==0.1.16
!pip install langchain-openai==0.0.5

from langchain.agents import initialize_agent, Tool
from langchain.agents.agent_types import AgentType
from langchain.memory import ConversationBufferMemory
from langchain.chat_models import ChatOpenAI
import os

from google.colab import userdata
import os
os.environ["OPENAI_API_KEY"]=userdata.get('openai')

llm=ChatOpenAI(temperature=0) #fact

def simple_calc(input: str) -> str:
    return str(eval(input))

tools=[Tool(name="Calculator",func=simple_calc,description="Useful for basic math")]

memory=ConversationBufferMemory(memory_key="chat_history")

agent=initialize_agent(tools=tools,llm=llm,memory=memory,verbose=True,)

response1=agent.run("What is 24 multiplied by 7")

response2=agent.run("Now add 400 to it.")

response1 = agent.run("What is 24 * 17?")
print("Agent:", response1)

response2 = agent.run("Now add 100 to it.")
print("Agent:", response2)

response3 = agent.run("Subtract 10.")
print("Agent:", response3)

### Fix remembering chat history

### File reader (txt),web search (duckduckgosearch)
### define function for file reader
### Tools

def file_reader_tool(query: str) -> str:
    try:
        with open("/content/training_data.txt", "r") as file:
            content = file.read()
            return content[:1000]
    except Exception as e:
        return f"Error reading file: {str(e)}"

!pip install duckduckgo-search

from langchain_community.tools import DuckDuckGoSearchRun

search=DuckDuckGoSearchRun()

tools = [

    Tool(
        name="FileReader",
        func=file_reader_tool,
        description="Reads content from a local text file called training_data.txt."
    ),
    Tool(
        name="WebSearch",
        func=search.run,
        description="Useful for answering questions about current events or facts using the internet."
    )
]

agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
    verbose=True,
    memory=memory
)

agent.run("Read the file and tell me the content")

import warnings
warnings.filterwarnings("ignore")

agent.run("What is the date today?")

print(agent.run("Who is the current CEO of OpenAI.Use websearch"))

### Assessment-> RAG Agent

